// <auto-generated />
namespace Garadice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class JobTrack : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobTrack));
        
        string IMigrationMetadata.Id
        {
            get { return "201608222117236_JobTrack"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
